
import { Button } from "@/components/ui/button"
import { ChefHat, Utensils, Sparkles } from "lucide-react"

const Index = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        {/* Gradient Orbs */}
        <div className="absolute top-0 left-0 w-[500px] h-[500px] bg-accent/30 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2" />
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary/20 rounded-full blur-3xl translate-x-1/2 -translate-y-1/2" />
        
        <div className="container mx-auto px-4 py-16 relative">
          <div className="max-w-3xl mx-auto text-center space-y-8">
            {/* Hero Content */}
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-muted animate-fade-in">
              <Sparkles className="w-4 h-4 text-primary" />
              <span className="text-sm text-primary">AI-Powered Meal Planning</span>
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent animate-fade-in">
              Your Personal AI Chef for 
              <br />
              Perfect Meal Plans
            </h1>
            
            <p className="text-xl text-secondary max-w-2xl mx-auto animate-fade-in">
              Generate personalized weekly meal plans tailored to your dietary needs, preferences, and available ingredients.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center animate-fade-in">
              <Button size="lg" className="bg-primary text-primary-foreground hover:bg-primary/90 min-w-[200px]">
                <ChefHat className="mr-2 h-5 w-5" />
                Get Started
              </Button>
              <Button size="lg" variant="outline" className="min-w-[200px]">
                <Utensils className="mr-2 h-5 w-5" />
                View Demo
              </Button>
            </div>
          </div>
          
          {/* Feature Cards */}
          <div className="grid md:grid-cols-3 gap-6 mt-20 animate-fade-in">
            <div className="p-6 rounded-lg border border-border bg-card hover:bg-accent/5 transition-colors">
              <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                <ChefHat className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-lg font-semibold mb-2">AI-Powered Plans</h3>
              <p className="text-secondary">Personalized meal plans generated by advanced AI to match your preferences.</p>
            </div>
            
            <div className="p-6 rounded-lg border border-border bg-card hover:bg-accent/5 transition-colors">
              <div className="h-12 w-12 rounded-full bg-accent/10 flex items-center justify-center mb-4">
                <Sparkles className="h-6 w-6 text-accent" />
              </div>
              <h3 className="text-lg font-semibold mb-2">Smart Ingredients</h3>
              <p className="text-secondary">Optimize your grocery shopping with intelligent ingredient suggestions.</p>
            </div>
            
            <div className="p-6 rounded-lg border border-border bg-card hover:bg-accent/5 transition-colors">
              <div className="h-12 w-12 rounded-full bg-success/10 flex items-center justify-center mb-4">
                <Utensils className="h-6 w-6 text-success" />
              </div>
              <h3 className="text-lg font-semibold mb-2">Balanced Nutrition</h3>
              <p className="text-secondary">Get perfectly balanced meals that meet your nutritional goals.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Index
