name: Test and Deploy

on:
  push:
    branches:
      - main  # Change to your target branch (e.g., master)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test  # Add your test command here (if any)

      - name: Build project
        run: npm run build

      - name: Create artifact (dist folder)
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT || 22 }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"  # Deploy the contents of the artifact
          target: /home/s4yusv/dev/js
          strip_components: 1  # Remove the top-level `dist` directory
          overwrite: true